name: CI

on:
  push:
    branches:
      - develop
      - master
      - feature/*
      - bugfix/*
      - release/*
  pull_request:
    branches: 
      - develop

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
